#!/usr/bin/env python3
"""
generate_page.py — HTML 웹페이지 생성 (직접 JS embed)
"""
import json, re
from pathlib import Path
from datetime import datetime, timezone, timedelta

KST = timezone(timedelta(hours=9))
SKILL_DIR = Path(__file__).parent.parent
TEMPLATE   = SKILL_DIR / "assets" / "template.html"
ARTICLES   = SKILL_DIR / "data" / "raw_articles.json"
INSIGHTS   = SKILL_DIR / "data" / "insights_report.json"
OUTPUT     = SKILL_DIR / "public" / "index.html"

def js_str(s):
    """Python str → safe JS string literal"""
    return json.dumps(str(s) if s else "", ensure_ascii=False)

def main():
    articles = json.load(open(ARTICLES))["articles"]
    insights = json.load(open(INSIGHTS))

    html = TEMPLATE.read_text(encoding="utf-8")

    # articles → JS array literal
    article_parts = ",".join(
        f'{{source:{js_str(a.get("source",""))},'
        f'title:{js_str(a.get("title",""))},'
        f'description:{js_str((a.get("description") or "")[:300])},'
        f'link:{js_str(a.get("link",""))}}}'
        for a in articles
    )
    articles_js = f"[{article_parts}]"

    # insights → JS object literal
    insights_js = json.dumps(insights, ensure_ascii=False)

    # Build the complete script block (data + render function)
    script = f'''<script>
window.ARTICLES={articles_js};
window.INSIGHTS={insights_js};

function escHtml(s){{
  if(!s)return'';
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}}

function render(data){{
  var d=new Date();
  document.getElementById('page-date').textContent=d.toLocaleDateString('ko-KR',{{year:'numeric',month:'long',day:'numeric',weekday:'long'}});
  document.querySelector('.footer').innerHTML='Generated by <strong>Hermes Daily Curation</strong> · '+(data.generated_at?new Date(data.generated_at).toLocaleString('ko-KR'):d.toLocaleString('ko-KR'));
  document.getElementById('summary').textContent=data.summary||'';

  var trendsEl=document.getElementById('trends');
  (data.trends||[]).forEach(function(t){{
    var impact=t.impact||'medium';
    trendsEl.innerHTML+='<div class="trend-card '+impact+'"><div class="trend-title">'+escHtml(t.title)+'</div><div class="trend-desc">'+escHtml(t.description)+'</div><div class="trend-meta"><span class="impact-badge impact-'+impact+'">'+impact+'</span>'+(t.sources||[]).map(function(s){{return'<span class="trend-source">• '+escHtml(s)+'</span>'}}).join('')+'</div></div>';
  }});

  var insightsEl=document.getElementById('insights');
  (data.insights||[]).forEach(function(i){{
    insightsEl.innerHTML+='<div class="insight-card"><div class="insight-title">💡 '+escHtml(i.title)+'</div><div class="insight-content">'+escHtml(i.content)+'</div>'+(i.trend_ref?'<span class="trend-ref"># '+escHtml(i.trend_ref)+'</span>':'')+'</div>';
  }});

  var actionsEl=document.getElementById('actions');
  (data.action_items||[]).forEach(function(a){{
    var p=a.priority||'medium';
    actionsEl.innerHTML+='<div class="action-item '+p+'"><div class="priority-dot"></div><div class="action-body"><div class="action-title">'+escHtml(a.title)+'</div><div class="action-desc">'+escHtml(a.description)+'</div><div class="action-meta"><span class="priority-label '+p+'">'+p+'</span><span class="effort-badge">⏱ '+escHtml(a.effort||'?')+'</span>'+(a.trend_ref?'<span class="trend-ref"># '+escHtml(a.trend_ref)+'</span>':'')+'</div></div></div>';
  }});

  var bi=data.business_impact||{{}};
  var bizEl=document.getElementById('biz-grid');
  if(bi.opportunities) bizEl.innerHTML+='<div class="biz-card opportunities"><h3>🟢 기회</h3><ul class="biz-list">'+bi.opportunities.map(function(o){{return'<li>'+escHtml(o)+'</li>'}}).join('')+'</ul></div>';
  if(bi.threats) bizEl.innerHTML+='<div class="biz-card threats"><h3>🔴 위협</h3><ul class="biz-list">'+bi.threats.map(function(o){{return'<li>'+escHtml(o)+'</li>'}}).join('')+'</ul></div>';
  if(bi.recommendations) bizEl.innerHTML+='<div class="biz-card recommendations" style="grid-column:1/-1"><h3>🟠 권고사항</h3><ul class="biz-list">'+bi.recommendations.map(function(o){{return'<li>'+escHtml(o)+'</li>'}}).join('')+'</ul></div>';
}}

document.addEventListener('DOMContentLoaded',function(){{
  render(window.INSIGHTS);
}});
</script>'''

    # Replace template script block
    html = re.sub(
        r'<script>\s*// ===== 데이터 로드.*?</script>',
        script,
        html,
        flags=re.DOTALL
    )

    now_kst = datetime.now(KST)
    html = html.replace("{{date}}", now_kst.strftime("%Y-%m-%d"))
    html = html.replace("{{generated_at}}", now_kst.strftime("%Y-%m-%d %H:%M KST"))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(html, encoding="utf-8")
    print(f"✅ HTML 생성 완료 ({OUTPUT.stat().st_size} bytes)")
    print(f"   기사:{len(articles)} 트렌드:{len(insights.get('trends',[]))} 인사이트:{len(insights.get('insights',[]))} 액션:{len(insights.get('action_items',[]))}")

if __name__ == "__main__":
    main()
